### ISSUE TITLE
Could not run the project with existing code?

### ISSUE THREAD

**Issue by srinubalsu** [jdanekrh/artemis-rest#2]
Hi,
I tried to build and run the existing code. I am not successful with that.

Error while setting up a Rest Proxy for Artemis? 

<details>

```
13-Nov-2018 16:23:05.549 SEVERE [http-nio-8084-exec-6] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener 
 java.lang.RuntimeException: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ119007: Cannot connect to server(s). Tried with all available servers.] 
        at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:54) 
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738) 
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181) 
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) 
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) 
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) 
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) 
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586) 
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:460) 
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1586) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:498) 
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) 
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) 
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) 
        at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1460) 
        at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:906) 
        at org.apache.catalina.manager.ManagerServlet.doGet(ManagerServlet.java:344) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) 
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614) 
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) 
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) 
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) 
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) 
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) 
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
        at java.lang.Thread.run(Thread.java:745) 
Caused by: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ119007: Cannot connect to server(s). Tried with all available servers.] 
        at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:790) 
        at org.apache.activemq.artemis.rest.MessageServiceManager.start(MessageServiceManager.java:150) 
        at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:50) 
        ... 48 more 

13-Nov-2018 16:23:06.404 SEVERE [http-nio-8084-exec-6] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener 
 java.lang.NullPointerException 
        at org.apache.activemq.artemis.rest.MessageServiceManager.stop(MessageServiceManager.java:209) 
        at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextDestroyed(RestMessagingBootstrapListener.java:61) 
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4785) 
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5404) 
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) 
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160) 
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) 
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) 
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) 
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586) 
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:460) 
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1586) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:498) 
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) 
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) 
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) 
        at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1460) 
        at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:906) 
        at org.apache.catalina.manager.ManagerServlet.doGet(ManagerServlet.java:344) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) 
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614) 
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) 
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) 
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) 
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) 
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) 
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
        at java.lang.Thread.run(Thread.java:745) 

13-Nov-2018 16:23:12.736 SEVERE [http-nio-8084-exec-8] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener 
 java.lang.RuntimeException: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ119007: Cannot connect to server(s). Tried with all available servers.] 
        at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:54) 
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738) 
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181) 
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) 
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) 
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) 
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) 
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586) 
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:460) 
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1586) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:498) 
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) 
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) 
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) 
        at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1460) 
        at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:906) 
        at org.apache.catalina.manager.ManagerServlet.doGet(ManagerServlet.java:344) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) 
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614) 
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) 
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) 
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) 
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) 
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) 
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
        at java.lang.Thread.run(Thread.java:745) 
Caused by: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ119007: Cannot connect to server(s). Tried with all available servers.] 
        at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:790) 
        at org.apache.activemq.artemis.rest.MessageServiceManager.start(MessageServiceManager.java:150) 
        at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:50) 
        ... 48 more 

13-Nov-2018 16:23:13.590 SEVERE [http-nio-8084-exec-8] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener 
 java.lang.NullPointerException 
        at org.apache.activemq.artemis.rest.MessageServiceManager.stop(MessageServiceManager.java:209) 
        at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextDestroyed(RestMessagingBootstrapListener.java:61) 
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4785) 
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5404) 
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) 
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160) 
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) 
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) 
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) 
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586) 
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:460) 
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1586) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:498) 
        at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) 
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) 
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) 
        at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1460) 
        at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:906) 
        at org.apache.catalina.manager.ManagerServlet.doGet(ManagerServlet.java:344) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) 
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) 
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614) 
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) 
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) 
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) 
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) 
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) 
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) 
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
        at java.lang.Thread.run(Thread.java:745) 
```
</p></details>

**Comment by srinubalsu** [comment]
Used the following pom.xml file


<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.jdanekrh</groupId>
    <artifactId>artemis-rest-integrated</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <dependencies>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxrs</artifactId>
            <version>3.0.11.Final</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxb-provider</artifactId>
            <version>3.0.19.Final</version>
        </dependency>
        <dependency>
            <groupId>org.apache.activemq.rest</groupId>
            <artifactId>artemis-rest</artifactId>
            <version>2.4.0</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
        </dependency>
    </dependencies>
</project>

**Comment by jirkadanek** [comment]
I started adding Arquillian test, just to be sure things are working, but I did not have it running yet (first time with Arquillian).

Where are you trying to run this? The "-integrated" subproject assumes that there is Artemis Broker already running in the same JVM, and there is InVM acceptor open. I think I put into the README.md there that this will work only in Wildfly, etc... The way I tested it was that I put the .war file into the Jetty that is embedded in Artemis.

**Comment by jirkadanek** [comment]
From `org.apache.catalina...` in the exception, I guess this is Tomcat. In that case, the -embedded subproject here should work. I did not try to run it recently.
